export { PACKAGE_NAME, PACKAGE_VERSION } from '#kernel/core/common/index.js';
export { resolveLocale, t } from '#kernel/core/i18n/index.js';
export type { Locale, MessageKey } from '#kernel/core/i18n/index.js';
export { DECKENT_DIR, BRAIN_DIR, CONFIG_FILE, PROJECT_CONFIG_PATH, CONFIG_SCHEMA_VERSION, CONFIG_CONTRACT_SINCE, OUTPUT_MODES } from '#kernel/core/common/index.js';
export type { OutputMode } from '#kernel/core/common/index.js';
export { DECKENT_VERSION, NODE_ENGINE_RANGE } from '#kernel/core/common/index.js';
export { SUPPORTED_LANGUAGES } from '#kernel/core/i18n/index.js';
export type { Params } from '#kernel/core/i18n/index.js';
export { DeckentError } from '#kernel/core/errors/index.js';
export type { ErrorCategory } from '#kernel/core/errors/index.js';
export { ErrorRegistry, ERROR_CODES, createCrossVerifyContractError, createExecutionAuthorityError, createExecutionAdmissionError, createDockerLifecycleError } from '#kernel/core/errors/index.js';
export { EXIT_CODES, exitCodeFor } from '#kernel/core/errors/index.js';
export type { ExitCode } from '#kernel/core/errors/index.js';
export { lintErrorRegistry, assertErrorRegistry } from '#kernel/core/errors/index.js';
export { formatHumanError, redactSensitive, buildCrashArtifact, writeCrashArtifact, reportFatal } from '#kernel/core/errors/index.js';
export type { CrashArtifactV1 } from '#kernel/core/errors/index.js';
export { ENVIRONMENT_KEYS, envValue } from '#kernel/core/platform/index.js';
export type { Environment } from '#kernel/core/platform/index.js';
export { normalizeGlobalScopePlatform, resolveGlobalScopePaths, resolveGlobalConfigPaths, resolveGlobalConfigReadPath } from '#kernel/core/platform/index.js';
export type { GlobalScopePlatform, GlobalScopePaths } from '#kernel/core/platform/index.js';
export { resolveDeckentHome, resolveBrainHome, deckentPath, brainPath } from '#kernel/core/platform/index.js';
export { detectHostMemory, suggestMaxWorkers, calcRecommendedMaxWorkers, suggestMaxWorkersFromCapacity, getSystemProfile } from '#kernel/core/platform/index.js';
export { detectEnvironment } from '#kernel/core/platform/index.js';
export { validatePath, validateExistingPath, validateTaskId } from '#kernel/core/validate/index.js';
export { deepMerge, readJsonFile, writeJsonAtomic } from '#kernel/core/utils/index.js';
export { formatDuration, estimateRemaining } from '#kernel/core/utils/index.js';
export { CORE_SCHEMA, registerConfigSection } from '#kernel/core/config/index.js';
export type { DeckentConfig, CoreConfig, ConfigSectionOptions } from '#kernel/core/config/index.js';
export { createDefaultConfig } from '#kernel/core/config/index.js';
export { ConfigValidationError } from '#kernel/core/config/index.js';
export type { ConfigWarning } from '#kernel/core/config/index.js';
export { validateConfig } from '#kernel/core/config/index.js';
export { interpolateConfig } from '#kernel/core/config/index.js';
export { configDisplayView } from '#kernel/core/config/index.js';
export { loadConfig, loadGlobalConfig, clearConfigCache } from '#kernel/core/config/index.js';
export type { ResolvedConfig, ConfigLoadOptions } from '#kernel/core/config/index.js';
export { saveGlobalConfig, writeConfig, withConfigWriteLock, pruneConfigBackups } from '#kernel/core/config/index.js';
export { healCorruptProjectConfig } from '#kernel/core/config/index.js';
export { getConfigMetadata } from '#kernel/core/config/index.js';
export { getConfigValue } from '#kernel/core/config/index.js';
export { resolveLocalOsActorId, resolveLocalOsPrincipal, principalToActor, assessActorAssurance, assertActorAssurance } from '#kernel/core/identity/index.js';
export type { VerifiedPrincipal, ActorContext } from '#kernel/core/identity/index.js';
export { isValidTenantId, tenantIsolationPath, resolveTenant, resolveCallerTenant, withTenant, currentTenant, tenantPath } from '#kernel/core/identity/index.js';
export { colorTier, shouldUseColor, stripAnsi } from '#kernel/core/output/index.js';
export { formatValue, formatTable, formatStatus, readMemoryKnowledge } from '#kernel/core/output/index.js';
export { emit, createEmitter } from '#kernel/core/output/index.js';
export type { OutputSink, EmitOptions } from '#kernel/core/output/index.js';
export { getConfigFieldDefault } from '#kernel/core/config-fields/index.js';
