export { PACKAGE_NAME, PACKAGE_VERSION } from './core/common/index.js';
export { resolveLocale, t } from './core/i18n/index.js';
export type { Locale, MessageKey } from './core/i18n/index.js';
export { DECKENT_DIR, BRAIN_DIR, CONFIG_FILE, PROJECT_CONFIG_PATH, CONFIG_SCHEMA_VERSION, OUTPUT_MODES } from './core/common/index.js';
export type { OutputMode } from './core/common/index.js';
export { DECKENT_VERSION, NODE_ENGINE_RANGE } from './core/common/index.js';
export { SUPPORTED_LANGUAGES } from './core/i18n/index.js';
export type { Params } from './core/i18n/index.js';
export { DeckentError } from './core/errors/index.js';
export type { ErrorCategory } from './core/errors/index.js';
export { ErrorRegistry, ERROR_CODES, createCrossVerifyContractError, createExecutionAuthorityError, createExecutionAdmissionError, createDockerLifecycleError } from './core/errors/index.js';
export { EXIT_CODES, exitCodeFor } from './core/errors/index.js';
export type { ExitCode } from './core/errors/index.js';
export { lintErrorRegistry, assertErrorRegistry } from './core/errors/index.js';
export { formatHumanError, redactSensitive, buildCrashArtifact, writeCrashArtifact, reportFatal } from './core/errors/index.js';
export type { CrashArtifactV1 } from './core/errors/index.js';
export { ENVIRONMENT_KEYS, envValue } from './core/platform/index.js';
export type { Environment } from './core/platform/index.js';
export { normalizeGlobalScopePlatform, resolveGlobalScopePaths, resolveGlobalConfigPaths, resolveGlobalConfigReadPath } from './core/platform/index.js';
export type { GlobalScopePlatform, GlobalScopePaths } from './core/platform/index.js';
export { resolveDeckentHome, resolveBrainHome, deckentPath, brainPath } from './core/platform/index.js';
export { detectHostMemory, suggestMaxWorkers, calcRecommendedMaxWorkers, suggestMaxWorkersFromCapacity, getSystemProfile } from './core/platform/index.js';
export { detectEnvironment } from './core/platform/index.js';
export { validatePath, validateExistingPath, validateTaskId } from './core/validate/index.js';
export { deepMerge, readJsonFile, writeJsonAtomic } from './core/utils/index.js';
export { formatDuration, estimateRemaining } from './core/utils/index.js';
export { CORE_SCHEMA, registerConfigSection } from './core/config/index.js';
export type { DeckentConfig, CoreConfig, ConfigSectionOptions } from './core/config/index.js';
export { createDefaultConfig } from './core/config/index.js';
export { ConfigValidationError } from './core/config/index.js';
export type { ConfigWarning } from './core/config/index.js';
export { validateConfig } from './core/config/index.js';
export { interpolateConfig } from './core/config/index.js';
export { configDisplayView } from './core/config/index.js';
export { loadConfig, loadGlobalConfig, clearConfigCache } from './core/config/index.js';
export type { ResolvedConfig, ConfigLoadOptions } from './core/config/index.js';
export { saveGlobalConfig, writeConfig, withConfigWriteLock, pruneConfigBackups } from './core/config/index.js';
export { healCorruptProjectConfig } from './core/config/index.js';
export { getConfigMetadata } from './core/config/index.js';
export { getConfigValue } from './core/config/index.js';
export { resolveLocalOsActorId, resolveLocalOsPrincipal, principalToActor, assessActorAssurance, assertActorAssurance } from './core/identity/index.js';
export type { VerifiedPrincipal, ActorContext } from './core/identity/index.js';
export { isValidTenantId, tenantIsolationPath, resolveTenant, resolveCallerTenant, withTenant, currentTenant, tenantPath } from './core/identity/index.js';
export { colorTier, shouldUseColor, stripAnsi } from './core/output/index.js';
export { formatValue, formatTable, formatStatus, readMemoryKnowledge } from './core/output/index.js';
export { emit, createEmitter } from './core/output/index.js';
export type { OutputSink, EmitOptions } from './core/output/index.js';
