export { ServiceFrameDecoder, ServiceFrameError, ServiceFrameStreamDecoder, encodeServiceFrame } from './internal/framing.js';
export type { ServiceFrameErrorCode } from './internal/framing.js';
export { LocalRuntimeSocketError } from './internal/endpoint.js';
export type { LocalRuntimeSocketErrorCode, LocalRuntimeSocketOptions } from './internal/endpoint.js';
export { acquireLocalRuntimeSocketGuard, startLocalRuntimeSocketServer } from './internal/server.js';
export type { LocalRuntimeSocketGuard, LocalRuntimeSocketServer, RuntimeServiceHandler } from './internal/server.js';
export type { RuntimeServiceStreamChannel } from './internal/stream-channel.js';
export type { RuntimeServiceTurnChannel } from './internal/event-channel.js';
export { requestLocalRuntime, streamLocalRuntime, turnLocalRuntime } from './internal/client.js';
export type { LocalPeerIdentity } from './internal/peer.js';
export { LocalPeerShutdownAuthentication, verifyLocalPeerIdentity } from './internal/authentication.js';
export { createLocalPeerSession } from './internal/authentication.js';
