import { t, resolveLocale, type Locale, type Params } from '#platform/core/i18n/index.js';
import { NODE_ENGINE_RANGE } from '#platform/core/common/index.js';
import { DeckentError, type ErrorCategory } from './error.js';
export interface ErrorEntry { readonly message: string; readonly suggestion?: string; readonly whatHappened?: string; readonly why?: string; readonly howToFix?: readonly string[] }
/** MCP_SANDBOX_COMMAND_UNREACHABLE (MCP-SANDBOX-PATHS): one catalog sentence per diagnosis kind (params name, kind, role, path, target
 * ('' = none), runner); `{targetSuffix}` is ' -> <target>' when the link target differs, the role is its own localized label. */
/** PATCH_LIMIT names the exceeded bound (params detail, observed, limit, field); an unknown or absent detail keeps the generic sentence. */
function patchLimit(p: Params, l: Locale): string {
  switch (p['detail']) {
    case 'bytes': return t('error.PATCH_LIMIT.bytes', p, l);
    case 'entries': return t('error.PATCH_LIMIT.entries', p, l);
    case 'depth': return t('error.PATCH_LIMIT.depth', p, l);
    case 'path': return t('error.PATCH_LIMIT.path', p, l);
    case 'time': return t('error.PATCH_LIMIT.time', p, l);
    case 'git-timeout': return t('error.PATCH_LIMIT.gitTimeout', p, l);
    case 'git-output': return t('error.PATCH_LIMIT.gitOutput', p, l);
    default: return t('error.PATCH_LIMIT', p, l);
  }
}
/** TASK_GRAPH_LIMIT (PARALLEL-S3) names the exceeded admission bound; an unknown detail keeps the generic sentence. */
function taskGraphLimit(p: Params, l: Locale): string {
  switch (p['detail']) {
    case 'tasks': return t('error.TASK_GRAPH_LIMIT.tasks', p, l);
    case 'edges': return t('error.TASK_GRAPH_LIMIT.edges', p, l);
    case 'depth': return t('error.TASK_GRAPH_LIMIT.depth', p, l);
    default: return t('error.TASK_GRAPH_LIMIT', p, l);
  }
}
/** TASK_GRAPH_INVALID (params reason = structural TaskGraphError code, path): cycle and missing dependency get their own sentence. */
function taskGraphInvalid(p: Params, l: Locale): string {
  switch (p['reason']) {
    case 'TASK_GRAPH_CYCLE': return t('error.TASK_GRAPH_INVALID.cycle', p, l);
    case 'TASK_DEPENDENCY_MISSING': return t('error.TASK_GRAPH_INVALID.dependencyMissing', p, l);
    default: return t('error.TASK_GRAPH_INVALID', { ...p, path: p['path'] ?? 'graph', reason: p['reason'] ?? 'invalid' }, l);
  }
}
function mcpSandboxUnreachable(p: Params, l: Locale): string {
  const name = String(p['name'] ?? '');
  if (p['kind'] === 'path-hidden') {
    const role = p['role'] === 'command' ? t('error.MCP_SANDBOX_COMMAND_UNREACHABLE.role.command', {}, l) : t('error.MCP_SANDBOX_COMMAND_UNREACHABLE.role.argument', {}, l);
    return t('error.MCP_SANDBOX_COMMAND_UNREACHABLE.pathHidden', { name, role, path: String(p['path'] ?? ''), targetSuffix: p['target'] ? ` -> ${String(p['target'])}` : '' }, l);
  }
  if (p['kind'] === 'package-runner') return t('error.MCP_SANDBOX_COMMAND_UNREACHABLE.packageRunner', { name, runner: String(p['runner'] ?? '') }, l);
  return t('error.MCP_SANDBOX_COMMAND_UNREACHABLE.containerDaemon', { name, runner: String(p['runner'] ?? '') }, l);
}
interface Definition { readonly category: ErrorCategory; readonly render: (params: Params, locale: Locale) => ErrorEntry }
const definitions: Readonly<Record<string, Definition>> = Object.freeze({
  BACKUP_STATE_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_STATE_CHANGED', p, l) }) },
  BACKUP_TARGET_IDENTITY_MISMATCH: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_TARGET_IDENTITY_MISMATCH', p, l) }) },
  BACKUP_RESTORE_INCOMPLETE: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_RESTORE_INCOMPLETE', p, l) }) },
  BACKUP_RESTORE_HOLD: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_RESTORE_HOLD', p, l) }) },
  BACKUP_INPUT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.BACKUP_INPUT_INVALID', p, l) }) },
  BACKUP_POLICY_DENIED: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_POLICY_DENIED', p, l) }) },
  BACKUP_PASSPHRASE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_PASSPHRASE_INVALID', p, l) }) },
  BACKUP_PATH_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_PATH_UNSAFE', p, l) }) },
  BACKUP_POLICY_UNREADABLE: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_POLICY_UNREADABLE', p, l) }) },
  BACKUP_TARGET_CONFIG_CONFLICT: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_TARGET_CONFIG_CONFLICT', p, l) }) },
  BACKUP_DIRECTORY_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_DIRECTORY_UNSAFE', p, l) }) },
  BACKUP_LIMIT: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_LIMIT', p, l) }) },
  BACKUP_KEY_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_KEY_INVALID', p, l) }) },
  BACKUP_SET_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_SET_INVALID', p, l) }) },
  BACKUP_MANIFEST_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_MANIFEST_INVALID', p, l) }) },
  BACKUP_FINGERPRINT_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_FINGERPRINT_INVALID', p, l) }) },
  BACKUP_LEDGER_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_LEDGER_INVALID', p, l) }) },
  BACKUP_STATE_MISSING: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_STATE_MISSING', p, l) }) },
  BACKUP_SET_EXISTS: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_SET_EXISTS', p, l) }) },
  BACKUP_TIMEOUT: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_TIMEOUT', p, l) }) },
  BACKUP_TARGET_NOT_EMPTY: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_TARGET_NOT_EMPTY', p, l) }) },
  BACKUP_SERVICE_RUNNING: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_SERVICE_RUNNING', p, l) }) },
  BACKUP_CUSTODY_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_CUSTODY_UNAVAILABLE', p, l) }) },
  BACKUP_IO: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_IO', p, l) }) },
  BACKUP_AUDIT_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_AUDIT_UNAVAILABLE', p, l) }) },
  BACKUP_SCHEDULE_IDENTITY_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_SCHEDULE_IDENTITY_REQUIRED', p, l) }) },
  BACKUP_SCHEDULE_SECRET_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.BACKUP_SCHEDULE_SECRET_REQUIRED', p, l) }) },
  INSTALLATION_IDENTITY_RELOCATED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_RELOCATED', p, l) }) },
  INSTALLATION_IDENTITY_RESOLUTION_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_RESOLUTION_INVALID', p, l) }) },
  INSTALLATION_IDENTITY_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_INVALID', p, l) }) },
  INSTALLATION_IDENTITY_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_UNAVAILABLE', p, l) }) },
  INSTALLATION_IDENTITY_MASKED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_MASKED', p, l) }) },
  INSTALLATION_IDENTITY_LOCKED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_LOCKED', p, l) }) },
  INSTALLATION_IDENTITY_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_UNSUPPORTED', p, l) }) },
  INSTALLATION_IDENTITY_SOURCE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_SOURCE_INVALID', p, l) }) },
  INSTALLATION_IDENTITY_MACHINE_BINDING_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_IDENTITY_MACHINE_BINDING_REQUIRED', p, l) }) },
  IDENTITY_PROFILE_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PROFILE_INVALID', p, l) }) },
  IDENTITY_PROFILE_NAMESPACE_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PROFILE_NAMESPACE_UNKNOWN', p, l) }) },
  IDENTITY_PROFILE_VERSION_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PROFILE_VERSION_UNKNOWN', p, l) }) },
  IDENTITY_PROFILE_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PROFILE_UNKNOWN', p, l) }) },
  IDENTITY_PROFILE_SHADOW: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PROFILE_SHADOW', p, l) }) },
  IDENTITY_PROFILE_DIGEST_MISMATCH: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PROFILE_DIGEST_MISMATCH', p, l) }) },
  IDENTITY_PREVIEW_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PREVIEW_INVALID', p, l) }) },
  IDENTITY_PREVIEW_SCOPE_DENIED: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PREVIEW_SCOPE_DENIED', p, l) }) },
  IDENTITY_PREVIEW_CONFLICT: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PREVIEW_CONFLICT', p, l) }) },
  IDENTITY_PREVIEW_LIMIT: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PREVIEW_LIMIT', p, l) }) },
  IDENTITY_PREVIEW_UNAVAILABLE: { category: 'usage', render: (p, l) => ({ message: t('error.IDENTITY_PREVIEW_UNAVAILABLE', p, l) }) },
  PROJECT_IDENTITY_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.PROJECT_IDENTITY_INVALID', p, l) }) },
  PROJECT_IDENTITY_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.PROJECT_IDENTITY_UNAVAILABLE', p, l) }) },
  PROJECT_IDENTITY_MASKED: { category: 'config', render: (p, l) => ({ message: t('error.PROJECT_IDENTITY_MASKED', p, l) }) },
  PROJECT_IDENTITY_LOCKED: { category: 'config', render: (p, l) => ({ message: t('error.PROJECT_IDENTITY_LOCKED', p, l) }) },

  CONFIG_SECRET_SECTION_REFUSED: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_SECRET_SECTION_REFUSED', p, l) }) },
  CONFIG_LAYER_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_LAYER_INVALID', p, l) }) },
  CONFIG_DIGEST_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_DIGEST_INVALID', p, l) }) },
  CONFIG_ARRAY_INDEX_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_ARRAY_INDEX_INVALID', p, l) }) },
  CONFIG_KEY_NOT_OBJECT: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_KEY_NOT_OBJECT', p, l) }) },
  CONFIG_METADATA_MISSING: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_METADATA_MISSING', p, l) }) },
  APPROVAL_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_INVALID', p, l) }) },
  APPROVAL_DENIED: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_DENIED', p, l) }) },
  APPROVAL_MISSING: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_MISSING', p, l) }) },
  APPROVAL_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_CONFLICT', p, l) }) },
  APPROVAL_EXPIRED: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_EXPIRED', p, l) }) },
  APPROVAL_INTEGRITY: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_INTEGRITY', p, l) }) },
  APPROVAL_STALE: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_STALE', p, l) }) },
  APPROVAL_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_REQUIRED', p, l) }) },
  APPROVAL_UNSETTLED: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_UNSETTLED', p, l) }) },
  SESSION_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.SESSION_REQUIRED', p, l) }) },
  SESSION_EXPIRED: { category: 'error', render: (p, l) => ({ message: t('error.SESSION_EXPIRED', p, l) }) },
  SESSION_INACTIVE: { category: 'error', render: (p, l) => ({ message: t('error.SESSION_INACTIVE', p, l) }) },
  INTEGRITY_KEY_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.INTEGRITY_KEY_UNAVAILABLE', p, l) }) },
  PREFIX_CACHE_SALT_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.PREFIX_CACHE_SALT_UNAVAILABLE', p, l) }) },

  CLI_INVOCATION_INPUT_LIMIT: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_INVOCATION_INPUT_LIMIT', p, l) }) },
  CLI_INVOCATION_INPUT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_INVOCATION_INPUT_INVALID', p, l) }) },
  CLI_INVOCATION_INPUT_TTY: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_INVOCATION_INPUT_TTY', p, l) }) },
  CLI_INVOCATION_INPUT_UNAVAILABLE: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_INVOCATION_INPUT_UNAVAILABLE', p, l) }) },
  CLI_CATALOG_INPUT_LIMIT: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CATALOG_INPUT_LIMIT', p, l) }) },
  CLI_CATALOG_INPUT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CATALOG_INPUT_INVALID', p, l) }) },
  CLI_CATALOG_INPUT_TTY: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CATALOG_INPUT_TTY', p, l) }) },
  CLI_CATALOG_INPUT_UNAVAILABLE: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CATALOG_INPUT_UNAVAILABLE', p, l) }) },
  RUNTIME_CHAT_EVENT_TOO_LARGE: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_CHAT_EVENT_TOO_LARGE', p, l) }) },
  TERMINAL_CHAT_NOT_CONFIGURED: { category: 'usage', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_NOT_CONFIGURED', p, l) }) },
  MODEL_CONNECT_PRICE_REQUIRED: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_PRICE_REQUIRED', p, l) }) },
  MODEL_CONNECT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_INVALID', p, l) }) },
  MODEL_CONNECT_NOT_CONNECTABLE: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_NOT_CONNECTABLE', p, l) }) },
  MODEL_CONNECT_ENDPOINT_FIXED: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_ENDPOINT_FIXED', p, l) }) },
  MODEL_CONNECT_ENDPOINT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_ENDPOINT_INVALID', p, l) }) },
  MODEL_CONNECT_MODEL_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_MODEL_UNKNOWN', p, l) }) },
  MODEL_CONNECT_DECLARATION_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CONNECT_DECLARATION_CONFLICT', p, l) }) },
  MODEL_CONNECT_KEY_NAME_UNAVAILABLE: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_KEY_NAME_UNAVAILABLE', p, l) }) },
  MODEL_CONNECT_SEED_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CONNECT_SEED_UNAVAILABLE', p, l) }) },
  MODEL_CONNECT_TARIFF_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CONNECT_TARIFF_UNKNOWN', p, l) }) },
  MODEL_CONNECT_TARIFF_UNVERIFIED: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CONNECT_TARIFF_UNVERIFIED', p, l) }) },
  MODEL_CONNECT_KEY_INSECURE: { category: 'usage', render: (p, l) => ({ message: t('error.MODEL_CONNECT_KEY_INSECURE', p, l) }) },
  MODEL_CONNECT_DEFINITION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CONNECT_DEFINITION_INVALID', p, l) }) },
  TERMINAL_DEFAULT_MODEL_PROJECT_LAYER: { category: 'config', render: (p, l) => ({ message: t('error.TERMINAL_DEFAULT_MODEL_PROJECT_LAYER', p, l) }) },
  TERMINAL_CHAT_MODEL_NOT_DECLARED: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_MODEL_NOT_DECLARED', p, l) }) },
  TERMINAL_CHAT_TRUNCATED: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_TRUNCATED', p, l) }) },
  TERMINAL_CHAT_EMPTY: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_EMPTY', p, l) }) },
  TERMINAL_CHAT_CANCELLED: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_CANCELLED', p, l) }) },
  TERMINAL_CHAT_INVOCATION_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_INVOCATION_FAILED', p, l) }) },
  TERMINAL_CHAT_INVOCATION_PENDING: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_INVOCATION_PENDING', p, l) }) },
  TERMINAL_CHAT_STREAM_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_STREAM_MISMATCH', p, l) }) },
  TERMINAL_CHAT_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.TERMINAL_CHAT_UNAVAILABLE', p, l) }) },
  AGENT_TURN_IN_PROGRESS: { category: 'error', render: (p, l) => ({ message: t('error.AGENT_TURN_IN_PROGRESS', p, l) }) },
  AGENT_TURN_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.AGENT_TURN_CONFLICT', p, l) }) },
  AGENT_TURN_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.AGENT_TURN_CORRUPT', p, l) }) },
  AGENT_TURN_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.AGENT_TURN_INVALID', p, l) }) },
  AGENT_TURN_REASONING_UNSUPPORTED: { category: 'usage', render: (p, l) => ({ message: t('error.AGENT_TURN_REASONING_UNSUPPORTED', p, l) }) },
  AGENT_TURN_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.AGENT_TURN_UNAVAILABLE', p, l) }) },
  TERMINAL_TTY_REQUIRED: { category: 'usage', render: (p, l) => ({ message: t('error.TERMINAL_TTY_REQUIRED', p, l) }) },
  INFERENCE_METRICS_UNREAD: { category: 'error', render: (p, l) => ({ message: t('error.INFERENCE_METRICS_UNREAD', p, l) }) },
  INFERENCE_PROFILE_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.INFERENCE_PROFILE_UNKNOWN', p, l) }) },
  DECISION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_INVALID', p, l) }) },
  DECISION_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_UNAVAILABLE', p, l) }) },
  DECISION_COMMAND_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_COMMAND_CONFLICT', p, l) }) },
  DECISION_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_CORRUPT', p, l) }) },
  DECISION_RECORD_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_RECORD_REQUIRED', p, l) }) },
  DECISION_OUTCOME_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_OUTCOME_UNKNOWN', p, l) }) },
  DECISION_ADVICE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_ADVICE_INVALID', p, l) }) },
  DECISION_POLICY_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_POLICY_INVALID', p, l) }) },
  DECISION_CASE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_CASE_INVALID', p, l) }) },
  DECISION_EVIDENCE_FUTURE: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_EVIDENCE_FUTURE', p, l) }) },
  DECISION_EVIDENCE_REFERENCE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_EVIDENCE_REFERENCE_INVALID', p, l) }) },
  DECISION_LIMIT_EXCEEDED: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_LIMIT_EXCEEDED', p, l) }) },
  DECISION_RECORD_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.DECISION_RECORD_INVALID', p, l) }) },
  MODEL_INVOCATION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_INVALID', p, l) }) },
  MODEL_INVOCATION_BINDING_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_BINDING_CONFLICT', p, l) }) },
  MODEL_INVOCATION_PROFILE_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_PROFILE_CONFLICT', p, l) }) },
  MODEL_INVOCATION_COMMAND_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_COMMAND_CONFLICT', p, l) }) },
  MODEL_INVOCATION_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_CORRUPT', p, l) }) },
  MODEL_INVOCATION_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_UNAVAILABLE', p, l) }) },
  MODEL_INVOCATION_OUTCOME_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_OUTCOME_UNKNOWN', p, l) }) },
  MODEL_INVOCATION_ACTIVATION_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_ACTIVATION_CONFLICT', p, l) }) },
  MODEL_INVOCATION_ALLOCATION_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_ALLOCATION_CONFLICT', p, l) }) },
  MODEL_INVOCATION_RESULT_LIMIT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_RESULT_LIMIT', p, l) }) },
  MODEL_INVOCATION_DELIVERY_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_DELIVERY_UNAVAILABLE', p, l) }) },
  PROVIDER_SPEND_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_INVALID', p, l) }) },
  PROVIDER_SPEND_RESULT_LIMIT: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_RESULT_LIMIT', p, l) }) },
  PROVIDER_SPEND_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_UNAVAILABLE', p, l) }) },
  PROVIDER_SPEND_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_CONFLICT', p, l) }) },
  PROVIDER_SPEND_EXHAUSTED: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_EXHAUSTED', p, l) }) },
  PROVIDER_SPEND_BUDGET_EXISTS: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_BUDGET_EXISTS', p, l) }) },
  PROVIDER_SPEND_BUDGET_ABSENT: { category: 'usage', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_BUDGET_ABSENT', p, l) }) },
  PROVIDER_SPEND_TARIFF_UNVERIFIED: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_TARIFF_UNVERIFIED', p, l) }) },
  PROVIDER_SPEND_FROZEN: { category: 'error', render: (p, l) => ({ message: t('error.PROVIDER_SPEND_FROZEN', p, l) }) },
  MODEL_INVOCATION_QUOTA_EXHAUSTED: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_QUOTA_EXHAUSTED', p, l) }) },
  MODEL_INVOCATION_CAPACITY_EXHAUSTED: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_INVOCATION_CAPACITY_EXHAUSTED', p, l) }) },
  OPENAI_CHAT_DEFINITION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_DEFINITION_INVALID', p, l) }) },
  OPENAI_CHAT_REQUEST_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_REQUEST_INVALID', p, l) }) },
  OPENAI_CHAT_REQUEST_TOO_LARGE: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_REQUEST_TOO_LARGE', p, l) }) },
  OPENAI_CHAT_RESPONSE_TOO_LARGE: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_RESPONSE_TOO_LARGE', p, l) }) },
  OPENAI_CHAT_TIMEOUT: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_TIMEOUT', p, l) }) },
  OPENAI_CHAT_CANCELLED: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_CANCELLED', p, l) }) },
  OPENAI_CHAT_TRANSPORT_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_TRANSPORT_UNKNOWN', p, l) }) },
  OPENAI_CHAT_MODEL_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_MODEL_MISMATCH', p, l) }) },
  OPENAI_CHAT_CACHE_SALT_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.OPENAI_CHAT_CACHE_SALT_UNAVAILABLE', p, l) }) },
  MODEL_ACTIVATION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_INVALID', p, l) }) },
  MODEL_ACTIVATION_REVISION_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_REVISION_CONFLICT', p, l) }) },
  MODEL_ACTIVATION_NOT_FOUND: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_NOT_FOUND', p, l) }) },
  MODEL_ACTIVATION_NOT_ACTIVE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_NOT_ACTIVE', p, l) }) },
  MODEL_ACTIVATION_BINDING_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_BINDING_CONFLICT', p, l) }) },
  MODEL_ACTIVATION_COMMAND_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_COMMAND_CONFLICT', p, l) }) },
  MODEL_ACTIVATION_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_CORRUPT', p, l) }) },
  MODEL_ACTIVATION_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_UNAVAILABLE', p, l) }) },
  MODEL_ACTIVATION_OUTCOME_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_OUTCOME_UNKNOWN', p, l) }) },
  MODEL_ACTIVATION_CATALOG_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_CATALOG_CONFLICT', p, l) }) },
  MODEL_ACTIVATION_DELIVERY_UNFIT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_ACTIVATION_DELIVERY_UNFIT', p, l) }) },
  WORKER_MODEL_UNPINNED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_UNPINNED', p, l) }) },
  WORKER_MODEL_ALIAS_REFUSED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_ALIAS_REFUSED', p, l) }) },
  WORKER_CHANNEL_NOT_ACTIVE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_CHANNEL_NOT_ACTIVE', p, l) }) },
  WORKER_CHANNEL_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_CHANNEL_MISMATCH', p, l) }) },
  WORKER_MODEL_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_UNKNOWN', p, l) }) },
  WORKER_MODEL_RETIRED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_RETIRED', p, l) }) },
  WORKER_MODEL_NOT_CURRENT: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_NOT_CURRENT', p, l) }) },
  WORKER_MODEL_NOT_ACTIVE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_NOT_ACTIVE', p, l) }) },
  WORKER_MODEL_CLI_TOO_OLD: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_CLI_TOO_OLD', p, l) }) },
  MODEL_CATALOG_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_INVALID', p, l) }) },
  MODEL_CATALOG_REVISION_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_REVISION_CONFLICT', p, l) }) },
  MODEL_CATALOG_NOT_FOUND: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_NOT_FOUND', p, l) }) },
  MODEL_CATALOG_NOT_ACTIVE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_NOT_ACTIVE', p, l) }) },
  MODEL_CATALOG_COMMAND_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_COMMAND_CONFLICT', p, l) }) },
  MODEL_CATALOG_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_CORRUPT', p, l) }) },
  MODEL_CATALOG_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_UNAVAILABLE', p, l) }) },
  MODEL_CATALOG_OUTCOME_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_OUTCOME_UNKNOWN', p, l) }) },
  WORKER_MODEL_BINDING_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_MODEL_BINDING_MISMATCH', p, l) }) },
  MODEL_CATALOG_ALIAS_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.MODEL_CATALOG_ALIAS_CONFLICT', p, l) }) },
  WORK_INPUT_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.WORK_INPUT_REQUIRED', p, l) }) },
  WORK_INPUT_TEMPLATE_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.WORK_INPUT_TEMPLATE_REQUIRED', p, l) }) },
  WORK_INPUT_TURN_LIMIT_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.WORK_INPUT_TURN_LIMIT_UNSUPPORTED', p, l) }) },
  WORK_INPUT_TURN_LIMIT_EXCEEDS_TEMPLATE: { category: 'error', render: (p, l) => ({ message: t('error.WORK_INPUT_TURN_LIMIT_EXCEEDS_TEMPLATE', p, l) }) },
  WORK_CLASS_NOT_REGISTERED: { category: 'error', render: (p, l) => ({ message: t('error.WORK_CLASS_NOT_REGISTERED', p, l) }) },
  WORKER_EFFORT_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_EFFORT_UNSUPPORTED', p, l) }) },
  TASK_DECISION_HUMAN_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.TASK_DECISION_HUMAN_REQUIRED', p, l) }) },
  RUN_PARKED: { category: 'error', render: (p, l) => ({ message: t('error.RUN_PARKED', p, l) }) },
  RUN_TERMINAL: { category: 'error', render: (p, l) => ({ message: t('error.RUN_TERMINAL', p, l) }) },
  RUN_NOT_PARKED: { category: 'error', render: (p, l) => ({ message: t('error.RUN_NOT_PARKED', p, l) }) },
  RUN_DECISION_NOT_READY: { category: 'error', render: (p, l) => ({ message: t('error.RUN_DECISION_NOT_READY', p, l) }) },
  RUN_DECISION_EXPIRED: { category: 'error', render: (p, l) => ({ message: t('error.RUN_DECISION_EXPIRED', p, l) }) },
  TASK_EVALUATION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVALUATION_INVALID', p, l) }) },
  TASK_EVALUATION_STALE: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVALUATION_STALE', p, l) }) },
  TASK_EVALUATION_NOT_READY: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVALUATION_NOT_READY', p, l) }) },
  TASK_EVALUATION_CRITERIA: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVALUATION_CRITERIA', p, l) }) },
  TASK_EVIDENCE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVIDENCE_INVALID', p, l) }) },
  TASK_EVIDENCE_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVIDENCE_UNAVAILABLE', p, l) }) },
  TASK_EVIDENCE_UNLINKED: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVIDENCE_UNLINKED', p, l) }) },
  EVALUATION_EVIDENCE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.EVALUATION_EVIDENCE_INVALID', p, l) }) },
  EVALUATION_EVIDENCE_INCOMPLETE: { category: 'error', render: (p, l) => ({ message: t('error.EVALUATION_EVIDENCE_INCOMPLETE', p, l) }) },
  EVALUATION_EVIDENCE_SCOPE: { category: 'error', render: (p, l) => ({ message: t('error.EVALUATION_EVIDENCE_SCOPE', p, l) }) },
  EVALUATION_EVIDENCE_LIMIT: { category: 'error', render: (p, l) => ({ message: t('error.EVALUATION_EVIDENCE_LIMIT', p, l) }) },
  EVALUATION_EVIDENCE_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.EVALUATION_EVIDENCE_CORRUPT', p, l) }) },
  EVALUATION_EVIDENCE_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.EVALUATION_EVIDENCE_UNAVAILABLE', p, l) }) },
  EXECUTION_NOT_CONFIGURED: { category: 'error', render: (p, l) => ({ message: t('error.EXECUTION_NOT_CONFIGURED', p, l) }) },
  EXECUTION_HOST_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.EXECUTION_HOST_UNSUPPORTED', p, l) }) },
  CANCELLATION_DELIVERY_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.CANCELLATION_DELIVERY_CONFLICT', p, l) }) },
  RECONCILIATION_NOT_CONFIGURED: { category: 'error', render: (p, l) => ({ message: t('error.RECONCILIATION_NOT_CONFIGURED', p, l) }) },
  RECONCILIATION_RECOVERY_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.RECONCILIATION_RECOVERY_INVALID', p, l) }) },
  RECONCILIATION_RUNTIME_LOOP_OPTIONS: { category: 'error', render: (p, l) => ({ message: t('error.RECONCILIATION_RUNTIME_LOOP_OPTIONS', p, l) }) },
  RECONCILIATION_RUNTIME_LOOP_RUNNING: { category: 'error', render: (p, l) => ({ message: t('error.RECONCILIATION_RUNTIME_LOOP_RUNNING', p, l) }) },
  CANCELLATION_RUNTIME_LOOP_OPTIONS: { category: 'error', render: (p, l) => ({ message: t('error.CANCELLATION_RUNTIME_LOOP_OPTIONS', p, l) }) },
  CANCELLATION_RUNTIME_LOOP_RUNNING: { category: 'error', render: (p, l) => ({ message: t('error.CANCELLATION_RUNTIME_LOOP_RUNNING', p, l) }) },
  LOCAL_RUNTIME_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.LOCAL_RUNTIME_UNSUPPORTED', p, l) }) },
  LOCAL_RUNTIME_OPTIONS: { category: 'error', render: (p, l) => ({ message: t('error.LOCAL_RUNTIME_OPTIONS', p, l) }) },
  RUNTIME_SHUTDOWN_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SHUTDOWN_UNAVAILABLE', p, l) }) },
  RUNTIME_AUTOSTART_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_AUTOSTART_FAILED', p, l) }) },
  TERMINAL_SCOPE_REQUIRED: { category: 'usage', render: (p, l) => ({ message: t('error.TERMINAL_SCOPE_REQUIRED', p, l) }) },
  LOCAL_RUNTIME_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.LOCAL_RUNTIME_UNAVAILABLE', p, l) }) },
  LOCAL_RUNTIME_ENDPOINT_UNSAFE: { category: 'error', render: (p, l) => ({ message: t('error.LOCAL_RUNTIME_ENDPOINT_UNSAFE', p, l) }) },
  LOCAL_RUNTIME_ALREADY_RUNNING: { category: 'error', render: (p, l) => ({ message: t('error.LOCAL_RUNTIME_ALREADY_RUNNING', p, l) }) },
  LOCAL_RUNTIME_TRANSPORT: { category: 'error', render: (p, l) => ({ message: t('error.LOCAL_RUNTIME_TRANSPORT', p, l) }) },
  RUNTIME_SERVICE_TRANSPORT: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_TRANSPORT', p, l) }) },
  RUNTIME_CHAT_TURN_TOO_LARGE: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_CHAT_TURN_TOO_LARGE', p, l) }) },
  RUNTIME_SERVICE_CORRELATION: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_CORRELATION', p, l) }) },
  RUNTIME_SERVICE_RESPONSE_LIMIT: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_RESPONSE_LIMIT', p, l) }) },
  RUNTIME_SERVICE_DELIVERY_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_DELIVERY_INVALID', p, l) }) },
  RUNTIME_SERVICE_OPTIONS: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_OPTIONS', p, l) }) },
  RUNTIME_SERVICE_BUSY: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_BUSY', p, l) }) },
  RUNTIME_SERVICE_STOPPING: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_STOPPING', p, l) }) },
  RUNTIME_SERVICE_RECOVERY_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_RECOVERY_FAILED', p, l) }) },
  RUNTIME_SERVICE_NOT_STOPPING: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_NOT_STOPPING', p, l) }) },
  SERVICE_SHUTDOWN_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_INVALID', p, l) }) },
  SERVICE_SHUTDOWN_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_CONFLICT', p, l) }) },
  SERVICE_SHUTDOWN_INSTANCE: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_INSTANCE', p, l) }) },
  SERVICE_SHUTDOWN_AUDIT_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_AUDIT_UNAVAILABLE', p, l) }) },
  SERVICE_SHUTDOWN_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_CORRUPT', p, l) }) },
  SERVICE_SHUTDOWN_NOT_ADMITTED: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_NOT_ADMITTED', p, l) }) },
  SERVICE_SHUTDOWN_OUTCOME_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.SERVICE_SHUTDOWN_OUTCOME_CONFLICT', p, l) }) },
  RUNTIME_SERVICE_SHUTDOWN_INCOMPLETE: { category: 'error', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_SHUTDOWN_INCOMPLETE', p, l) }) },
  // H34 S3 Q1 (owner 2026-09-27 evening decision 6): `runtime serve` refuses to start while one of its own scopes is already pinned
  // to another company (config/ledger mismatch; same 'config' category, exit 78, as CONFIG_VERSION_UNSUPPORTED/LAYOUT_VERSION_UNSUPPORTED
  // and the INSTALLATION_PROFILE_* siblings above — the operator's remedy is their own company.id or ledger, not a transport retry).
  // Locale key not yet present (locale files are lead-owned, common; same temporary pattern as POLICY_APPROVAL_UNSUPPORTED /
  // INSTALLATION_PROFILE_APPROVAL_UNSUPPORTED before their keys were added). See i18n-delta.json for the suggested en/tr text.
  RUN_PROGRESSION_SCOPE_SKIPPED: { category: 'config', render: (p, l) => ({ message: t('error.RUN_PROGRESSION_SCOPE_SKIPPED', p, l) }) },
  RUNTIME_SERVICE_SCOPE_FOREIGN: { category: 'config', render: (p, l) => ({ message: t('error.RUNTIME_SERVICE_SCOPE_FOREIGN', p, l) }) },
  RUN_WORKSPACE_CUSTODY_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.RUN_WORKSPACE_CUSTODY_CONFLICT', p, l) }) },
  RUN_WORKSPACE_CUSTODY_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.RUN_WORKSPACE_CUSTODY_CORRUPT', p, l) }) },
  WORKSPACE_CUSTODY_UNCONVERTIBLE: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_CUSTODY_UNCONVERTIBLE', p, l) }) },
  WORKSPACE_REQUEST_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_REQUEST_INVALID', p, l) }) },
  WORKSPACE_OPTIONS_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_OPTIONS_INVALID', p, l) }) },
  WORKSPACE_UNSAFE: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_UNSAFE', p, l) }) },
  WORKSPACE_IDENTITY_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_IDENTITY_CONFLICT', p, l) }) },
  WORKSPACE_ALLOCATION_INCOMPLETE: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_ALLOCATION_INCOMPLETE', p, l) }) },
  WORKSPACE_GIT_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.WORKSPACE_GIT_FAILED', p, l) }) },
  CANCELLATION_DELIVERY_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.CANCELLATION_DELIVERY_CORRUPT', p, l) }) },
  CANCELLATION_NOT_CONFIGURED: { category: 'error', render: (p, l) => ({
    message: t('error.CANCELLATION_NOT_CONFIGURED', { ...p, missing: p['missing'] ?? t('output.unknown', {}, l) }, l),
    suggestion: t('error.CANCELLATION_NOT_CONFIGURED.init', {}, l),
  }) },
  EXECUTION_PROFILE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.EXECUTION_PROFILE_INVALID', p, l) }) },
  EXECUTION_RESOURCE_CEILING: { category: 'config', render: (p, l) => ({ message: t('error.EXECUTION_RESOURCE_CEILING', p, l) }) },
  TASK_GRAPH_LIMIT: { category: 'config', render: (p, l) => ({ message: taskGraphLimit(p, l) }) },
  TASK_GRAPH_INVALID: { category: 'usage', render: (p, l) => ({ message: taskGraphInvalid(p, l) }) },
  PATCH_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_CORRUPT', p, l) }) },
  PATCH_INTEGRATION_PENDING: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_INTEGRATION_PENDING', p, l) }) },
  PATCH_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_CONFLICT', p, l) }) },
  PATCH_BASE_ADVANCED: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_BASE_ADVANCED', p, l) }) },
  // K6 (owner 2026-09-30 A): the work target enforces task scope; params count, paths (first 16, repository-relative), omitted.
  PATCH_SCOPE_VIOLATION: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_SCOPE_VIOLATION', p, l) }) },
  PATCH_SCOPE_UNDECLARED: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_SCOPE_UNDECLARED', p, l) }) },
  WORK_TARGET_PATH_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_PATH_INVALID', p, l) }) },
  WORK_TARGET_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_UNSAFE', p, l) }) },
  WORK_TARGET_IN_DATA_ROOT: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_IN_DATA_ROOT', p, l) }) },
  WORK_TARGET_IS_PROJECT: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_IS_PROJECT', p, l) }) },
  WORK_TARGET_NOT_WORKTREE: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_NOT_WORKTREE', p, l) }) },
  WORK_TARGET_SHARES_PROJECT_REPOSITORY: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_SHARES_PROJECT_REPOSITORY', p, l) }) },
  WORK_TARGET_ALTERNATES: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_ALTERNATES', p, l) }) },
  WORK_TARGET_BASE_MISSING: { category: 'config', render: (p, l) => ({ message: t('error.WORK_TARGET_BASE_MISSING', p, l) }) },
  EFFECT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.EFFECT_INVALID', p, l) }) },
  EFFECT_OPERATION_UNKNOWN: { category: 'config', render: (p, l) => ({ message: t('error.EFFECT_OPERATION_UNKNOWN', p, l) }) },
  EFFECT_APPROVAL_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_APPROVAL_REQUIRED', p, l) }) },
  EFFECT_PRECONDITION_CHANGED: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_PRECONDITION_CHANGED', p, l) }) },
  EFFECT_TARGET_BUSY: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_TARGET_BUSY', p, l) }) },
  EFFECT_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_CONFLICT', p, l) }) },
  EFFECT_OUTCOME_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_OUTCOME_UNKNOWN', p, l) }) },
  EFFECT_NOT_COMPENSABLE: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_NOT_COMPENSABLE', p, l) }) },
  EFFECT_REJECTED: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_REJECTED', p, l) }) },
  EFFECT_TARGET_CHANGED: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_TARGET_CHANGED', p, l) }) },
  // POLICY-ADMIN I5-i: a generic producer refused an authority operation before any policy, ledger or target access.
  OPERATION_SURFACE_RESTRICTED: { category: 'error', render: (p, l) => ({ message: t('error.OPERATION_SURFACE_RESTRICTED', p, l) }) },
  // POLICY-HARDEN K3: only the authority surface may allow an approval of an authority operation; a deny stays open everywhere.
  APPROVAL_SURFACE_RESTRICTED: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_SURFACE_RESTRICTED', p, l) }) },
  // B1 APPROVAL-ASSURANCE: MCP never allows; an allow below the approval's minimum assurance (Core's, raised by policy) is refused.
  APPROVAL_ATTENDED_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_ATTENDED_REQUIRED', p, l) }) },
  APPROVAL_ASSURANCE_INSUFFICIENT: { category: 'error', render: (p, l) => ({ message: t('error.APPROVAL_ASSURANCE_INSUFFICIENT', p, l) }) },
  // MCP-CLIENT scoped registry and approval (`deckent mcp add|add-json|list|get|remove|approve`).
  MCP_SERVER_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_SERVER_UNKNOWN', p, l) }) },
  MCP_SERVER_EXISTS: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_SERVER_EXISTS', p, l) }) },
  MCP_SERVER_SCOPE_AMBIGUOUS: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_SERVER_SCOPE_AMBIGUOUS', p, l) }) },
  MCP_SERVER_ENTRY_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.MCP_SERVER_ENTRY_INVALID', p, l) }) },
  MCP_SERVER_NAME_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_SERVER_NAME_INVALID', p, l) }) },
  MCP_SANDBOX_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MCP_SANDBOX_UNAVAILABLE', p, l) }) },
  MCP_SERVER_START_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.MCP_SERVER_START_FAILED', p, l) }) },
  // MCP-SANDBOX-PATHS (2026-09-29): the default realm's bubblewrap view cannot reach what the server needs (params: name, kind, and role/path/target
  // or runner); the sentence is chosen by the diagnosis kind.
  MCP_SANDBOX_COMMAND_UNREACHABLE: { category: 'error', render: (p, l) => ({ message: mcpSandboxUnreachable(p, l) }) },
  MCP_TOOL_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_TOOL_UNKNOWN', p, l) }) },
  MCP_APPROVAL_NEEDS_TERMINAL: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_APPROVAL_NEEDS_TERMINAL', p, l) }) },
  MCP_REGISTRY_FILE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.MCP_REGISTRY_FILE_INVALID', p, l) }) },
  MCP_SERVER_NOT_TRUSTED: { category: 'usage', render: (p, l) => ({ message: t('error.MCP_SERVER_NOT_TRUSTED', p, l) }) },
  MCP_TRUST_STORE_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MCP_TRUST_STORE_UNAVAILABLE', p, l) }) },
  EFFECT_TARGET_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_TARGET_UNAVAILABLE', p, l) }) },
  EFFECT_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.EFFECT_CORRUPT', p, l) }) },
  ADOPTION_TARGET_DENIED: { category: 'config', render: (p, l) => ({ message: t('error.ADOPTION_TARGET_DENIED', p, l) }) },
  ADOPTION_TARGET_MISSING: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_TARGET_MISSING', p, l) }) },
  ADOPTION_TARGET_CHECKED_OUT: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_TARGET_CHECKED_OUT', p, l) }) },
  ADOPTION_BASE_CHANGED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_BASE_CHANGED', p, l) }) },
  ADOPTION_NOT_DELIVERED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_NOT_DELIVERED', p, l) }) },
  ADOPTION_NOT_ACCEPTED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_NOT_ACCEPTED', p, l) }) },
  ADOPTION_TARGET_BUSY: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_TARGET_BUSY', p, l) }) },
  ADOPTION_SUPERSEDED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_SUPERSEDED', p, l) }) },
  ADOPTION_TARGET_MOVED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_TARGET_MOVED', p, l) }) },
  ADOPTION_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_CONFLICT', p, l) }) },
  ADOPTION_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_CORRUPT', p, l) }) },
  ADOPTION_VERIFICATION_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_FAILED', p, l) }) },
  ADOPTION_VERIFICATION_PENDING: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_PENDING', p, l) }) },
  ADOPTION_VERIFICATION_UNSETTLED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_UNSETTLED', p, l) }) },
  ADOPTION_VERIFICATION_CANCELLED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_CANCELLED', p, l) }) },
  ADOPTION_VERIFICATION_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_MISMATCH', p, l) }) },
  ADOPTION_NOT_VERIFIED: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_NOT_VERIFIED', p, l) }) },
  ADOPTION_VERIFICATION_CRITERIA_WEAKER: { category: 'error', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_CRITERIA_WEAKER', p, l) }) },
  ADOPTION_VERIFICATION_NOT_CONFIGURED: { category: 'config', render: (p, l) => ({ message: t('error.ADOPTION_VERIFICATION_NOT_CONFIGURED', p, l) }) },
  PATCH_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_UNSUPPORTED', p, l) }) },
  PATCH_LIMIT: { category: 'error', render: (p, l) => ({ message: patchLimit(p, l) }) },
  PATCH_UNSAFE: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_UNSAFE', p, l) }) },
  WORKER_OBSERVATION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_OBSERVATION_INVALID', p, l) }) },
  WORKER_OBSERVATION_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_OBSERVATION_UNAVAILABLE', p, l) }) },
  WORKER_EVENTS_SEAL_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_EVENTS_SEAL_FAILED', p, l) }) },
  PATCH_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.PATCH_UNAVAILABLE', p, l) }) },
  NATIVE_CREDENTIAL_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.NATIVE_CREDENTIAL_UNAVAILABLE', p, l) }) },
  NATIVE_CONNECTION_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.NATIVE_CONNECTION_UNAVAILABLE', p, l) }) },
  TASK_EVALUATOR_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVALUATOR_INVALID', p, l) }) },
  TASK_KIND_NOT_REGISTERED: { category: 'error', render: (p, l) => ({ message: t('error.TASK_KIND_NOT_REGISTERED', p, l) }) },
  TASK_EVALUATOR_NOT_REGISTERED: { category: 'error', render: (p, l) => ({ message: t('error.TASK_EVALUATOR_NOT_REGISTERED', p, l) }) },
  EXECUTION_REGISTRY_VALIDATOR_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.EXECUTION_REGISTRY_VALIDATOR_INVALID', p, l) }) },
  RUN_ADMISSION_NOT_CONFIGURED: { category: 'error', render: (p, l) => ({ message: t('error.RUN_ADMISSION_NOT_CONFIGURED', p, l) }) },
  RUN_STORE_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.RUN_STORE_CORRUPT', p, l) }) },
  RUN_STORE_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.RUN_STORE_CONFLICT', p, l), suggestion: t('remedy.RUN_STORE_CONFLICT', p, l) }) },
  HANDOFF_SOURCE_NOT_ACCEPTED: { category: 'error', render: (p, l) => ({ message: t('error.HANDOFF_SOURCE_NOT_ACCEPTED', p, l) }) },
  HANDOFF_ARTIFACT_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.HANDOFF_ARTIFACT_MISMATCH', p, l) }) },
  HANDOFF_PATCH_UNAPPLICABLE: { category: 'error', render: (p, l) => ({ message: t('error.HANDOFF_PATCH_UNAPPLICABLE', p, l) }) },
  HANDOFF_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.HANDOFF_INVALID', p, l) }) },
  HANDOFF_LIMIT_EXCEEDED: { category: 'error', render: (p, l) => ({ message: t('error.HANDOFF_LIMIT_EXCEEDED', p, l) }) },
  RUN_NOT_FOUND: { category: 'error', render: (p, l) => ({ message: t('error.RUN_NOT_FOUND', p, l) }) },
  RUN_COMMAND_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.RUN_COMMAND_CONFLICT', p, l) }) },
  RUN_POOL_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.RUN_POOL_REQUIRED', p, l) }) },
  RUN_POOL_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.RUN_POOL_CONFLICT', p, l) }) },
  RUN_POOL_FULL: { category: 'error', render: (p, l) => ({ message: t('error.RUN_POOL_FULL', p, l) }) },
  RUN_POOL_CAPACITY_OCCUPIED: { category: 'error', render: (p, l) => ({ message: t('error.RUN_POOL_CAPACITY_OCCUPIED', p, l) }) },
  RUN_POOL_HELD: { category: 'error', render: (p, l) => ({ message: t('error.RUN_POOL_HELD', p, l) }) },
  RUN_CAPACITY_OR_ORDER: { category: 'error', render: (p, l) => ({ message:
    ['site', 'reason', 'readyCount', 'delayedCount', 'executionOccupied', 'executionSlots'].every(key => p[key] !== undefined)
      ? (p.eligibilityGapMs !== undefined ? t('error.RUN_CAPACITY_OR_ORDER.delayed', p, l) : t('error.RUN_CAPACITY_OR_ORDER.detail', p, l))
      : t('error.RUN_CAPACITY_OR_ORDER', p, l) }) },
  INVENTORY_QUERY_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.INVENTORY_QUERY_INVALID', p, l) }) },
  ATTEMPT_NOT_FOUND: { category: 'error', render: (p, l) => ({ message: t('error.ATTEMPT_NOT_FOUND', p, l) }) },
  INVENTORY_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.INVENTORY_UNAVAILABLE', p, l) }) },
  MONITOR_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.MONITOR_UNAVAILABLE', p, l) }) },
  DISPATCH_INVENTORY_LIMIT: { category: 'usage', render: (p, l) => ({ message: t('error.DISPATCH_INVENTORY_LIMIT', p, l) }) },
  AUTHENTICATION_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.AUTHENTICATION_REQUIRED', p, l) }) },
  AUTHENTICATION_SCOPE_DENIED: { category: 'error', render: (p, l) => ({ message: t('error.AUTHENTICATION_SCOPE_DENIED', p, l) }) },
  POLICY_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_UNAVAILABLE', p, l) }) },
  POLICY_DENIED: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_DENIED', p, l) }) },
  SCOPE_UNKNOWN: { category: 'error', render: (p, l) => ({ message: t('error.SCOPE_UNKNOWN', p, l) }) },
  // C12 Q8: require-approval outside the operation catalog (no broker there yet). Typed and distinct from POLICY_DENIED.
  POLICY_APPROVAL_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_APPROVAL_UNSUPPORTED', p, l) }) },
  // POLICY-ADMIN P1-P3: typed refusals of policy.administer@1; no surface maps them yet (authority producer surface is P5).
  POLICY_DELEGATION_EXCEEDS: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_DELEGATION_EXCEEDS', p, l) }) },
  POLICY_CHANGE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_CHANGE_INVALID', p, l) }) },
  POLICY_CHANGE_TOO_LARGE: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_CHANGE_TOO_LARGE', p, l) }) },
  POLICY_ADMINISTER_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.POLICY_ADMINISTER_UNSUPPORTED', p, l) }) },
  // SECRET-K1: typed refusals of the SecretStore port (engine) and its backends. No parameter or cause ever carries a secret value or store
  // content; the texts interpolate only {backend}, {path} (the store directory) and {name}.
  SECRET_NAME_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.SECRET_NAME_INVALID', p, l) }) },
  SECRET_VALUE_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.SECRET_VALUE_INVALID', p, l) }) },
  SECRET_STORE_UNKNOWN: { category: 'config', render: (p, l) => ({ message: t('error.SECRET_STORE_UNKNOWN', p, l) }) },
  SECRET_STORE_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_UNAVAILABLE', p, l) }) },
  SECRET_STORE_UNSAFE: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_UNSAFE', p, l) }) },
  SECRET_STORE_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_CORRUPT', p, l) }) },
  SECRET_STORE_READ_ONLY: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_READ_ONLY', p, l) }) },
  SECRET_STORE_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_UNSUPPORTED', p, l) }) },
  // SECRET-BOUNDS (Astra 2185 R5): the change would grow the store document past the bound its reader enforces (params backend, maxBytes;
  // nothing written).
  SECRET_STORE_FULL: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_FULL', p, l) }) },
  SECRET_STORE_DOWNGRADE_UNCONFIRMED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_DOWNGRADE_UNCONFIRMED', p, l) }) },
  SECRET_STORE_SWITCH_UNVERIFIED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_SWITCH_UNVERIFIED', p, l) }) },
  SECRET_STORE_SWITCH_DENIED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_SWITCH_DENIED', p, l) }) },
  // Astra 2456 P1-1: another secret change or store switch holds the installation's custody section past the wait bound (nothing changed).
  SECRET_STORE_ENV_UNCONFIRMED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_ENV_UNCONFIRMED', p, l) }) },
  SECRET_STORE_BUSY: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_BUSY', p, l) }) },
  // A store switch published another store after this change opened {backend}: nothing was decided, recorded or written.
  SECRET_STORE_CHANGED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_STORE_CHANGED', p, l) }) },
  // SECRET-WRITE: no allow grant on `secret`/`set|delete` for this name (params action, name — never a value); the text names the grant to add.
  // The prompt of `secret set` was ended with Ctrl-C (nothing sent).
  SECRET_CHANGE_DENIED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_CHANGE_DENIED', p, l) }) },
  SECRET_INPUT_CANCELLED: { category: 'error', render: (p, l) => ({ message: t('error.SECRET_INPUT_CANCELLED', p, l) }) },
  PERMISSION_MODE_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.PERMISSION_MODE_CONFLICT', p, l) }) },
  PERMISSION_MODE_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.PERMISSION_MODE_UNSUPPORTED', p, l) }) },
  PERMISSION_MODE_DENIED: { category: 'error', render: (p, l) => ({ message: t('error.PERMISSION_MODE_DENIED', p, l) }) },
  PERMISSION_MODE_LOCKED: { category: 'error', render: (p, l) => ({ message: t('error.PERMISSION_MODE_LOCKED', p, l) }) },
  PERMISSION_MODE_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.PERMISSION_MODE_INVALID', p, l) }) },
  AUDIT_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.AUDIT_INVALID', p, l) }) },
  AUDIT_INTEGRITY: { category: 'error', render: (p, l) => ({ message: t('error.AUDIT_INTEGRITY', p, l) }) },
  AUDIT_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.AUDIT_CONFLICT', p, l) }) },
  AUDIT_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.AUDIT_UNAVAILABLE', p, l) }) },
  MANAGED_FILE_MISSING: { category: 'error', render: (p, l) => ({ message: t('error.MANAGED_FILE_MISSING', p, l) }) },
  MANAGED_FILE_UNSAFE: { category: 'error', render: (p, l) => ({ message: t('error.MANAGED_FILE_UNSAFE', p, l) }) },
  MANAGED_FILE_UNSUPPORTED: { category: 'error', render: (p, l) => ({ message: t('error.MANAGED_FILE_UNSUPPORTED', p, l) }) },
  MANAGED_FILE_OUTSIDE_ROOT: { category: 'error', render: (p, l) => ({ message: t('error.MANAGED_FILE_OUTSIDE_ROOT', p, l) }) },
  ATTEMPT_STORE_VERSION: { category: 'error', render: (p, l) => ({ message: t('error.ATTEMPT_STORE_VERSION', p, l) }) },
  LEDGER_RESET_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.LEDGER_RESET_REQUIRED', p, l) }) },
  LEDGER_MIGRATION_EVIDENCE_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.LEDGER_MIGRATION_EVIDENCE_REQUIRED', p, l) }) },
  ATTEMPT_STORE_BUSY: { category: 'error', render: (p, l) => ({ message: t('error.ATTEMPT_STORE_BUSY', p, l) }) },
  ATTEMPT_STORE_OPTIONS: { category: 'config', render: (p, l) => ({ message: t('error.ATTEMPT_STORE_OPTIONS', p, l) }) },
  // DEPS-P0: node:sqlite predates the 3.51.3 floor; the text names the floor literally and {floor} is the Node engine range (default param).
  ATTEMPT_STORE_SQLITE_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.ATTEMPT_STORE_SQLITE_UNSUPPORTED', p, l) }) },
  ATTEMPT_STORE_READ_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.ATTEMPT_STORE_READ_UNAVAILABLE', p, l) }) },
  ATTEMPT_STORE_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.ATTEMPT_STORE_CORRUPT', p, l) }) },
  DISPATCH_CORRUPT: { category: 'error', render: (p, l) => ({ message: t('error.DISPATCH_CORRUPT', p, l) }) },
  DISPATCH_ARTIFACT_REQUIRED: { category: 'error', render: (p, l) => ({ message: t('error.DISPATCH_ARTIFACT_REQUIRED', p, l) }) },
  DISPATCH_CONFLICT: { category: 'error', render: (p, l) => ({ message: t('error.DISPATCH_CONFLICT', p, l) }) },
  DISPATCH_NOT_ADMITTED: { category: 'error', render: (p, l) => ({ message: t('error.DISPATCH_NOT_ADMITTED', p, l) }) },
  DISPATCH_PROFILE_VALIDATION_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.DISPATCH_PROFILE_VALIDATION_REQUIRED', p, l) }) },

  CONFIG_FILE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_FILE_INVALID', p, l), suggestion: t('remedy.CONFIG_FILE_INVALID', p, l), whatHappened: t('what.CONFIG_FILE_INVALID', p, l), why: t('why.CONFIG_FILE_INVALID', p, l), howToFix: Object.freeze(t('fix.CONFIG_FILE_INVALID', p, l).split('\n')) }) },
  UNSUPPORTED_PLATFORM: { category: 'error', render: (p, l) => ({ message: t('error.UNSUPPORTED_PLATFORM', p, l) }) },
  HOME_NOT_RESOLVED: { category: 'config', render: (p, l) => ({ message: t('error.HOME_NOT_RESOLVED', p, l) }) },
  PATH_TRAVERSAL: { category: 'usage', render: (p, l) => ({ message: t('error.PATH_TRAVERSAL', p, l) }) },
  INVALID_TASK_ID: { category: 'usage', render: (p, l) => ({ message: t('error.INVALID_TASK_ID', p, l) }) },
  ACTOR_UNVERIFIED: { category: 'usage', render: (p, l) => ({ message: t('error.ACTOR_UNVERIFIED', p, l) }) },
  CONFIG_UNSAFE_KEY: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_UNSAFE_KEY', p, l) }) },
  CONFIG_BACKUP_PRUNE_FAILED: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_BACKUP_PRUNE_FAILED', p, l) }) },
  CONFIG_READ_IO_HOLD: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_READ_IO_HOLD', p, l) }) },
  CONFIG_CONCURRENT_REVISION_HOLD: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_CONCURRENT_REVISION_HOLD', p, l) }) },
  CONFIG_APPROVAL_STALE: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_APPROVAL_STALE', p, l) }) },
  CONFIG_APPROVAL_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_APPROVAL_REQUIRED', p, l) }) },
  CONFIG_WRITE_LOCKED: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_WRITE_LOCKED', p, l) }) },
  CONFIG_VERSION_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_VERSION_UNSUPPORTED', p, l) }) },
  CONFIG_SECTION_DUPLICATE: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_SECTION_DUPLICATE', p, l) }) },
  CONFIG_RECORD_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_RECORD_INVALID', p, l) }) },
  CONFIG_SECTION_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_SECTION_INVALID', p, l) }) },
  CONFIG_KEY_UNKNOWN: { category: 'usage', render: (p, l) => ({ message: t('error.CONFIG_KEY_UNKNOWN', p, l) }) },
  LAYOUT_VERSION_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.LAYOUT_VERSION_UNSUPPORTED', p, l) }) },
  LAYOUT_ROOT_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.LAYOUT_ROOT_INVALID', p, l) }) },
  LAYOUT_RESOURCE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.LAYOUT_RESOURCE_INVALID', p, l) }) },
  LAYOUT_RESOURCE_UNKNOWN: { category: 'config', render: (p, l) => ({ message: t('error.LAYOUT_RESOURCE_UNKNOWN', p, l) }) },
  LAYOUT_PATH_UNEXPRESSIBLE: { category: 'config', render: (p, l) => ({ message: t('error.LAYOUT_PATH_UNEXPRESSIBLE', p, l) }) },
  CONFIG_VALIDATION: { category: 'config', render: (p, l) => ({ message: t('error.CONFIG_VALIDATION', p, l) }) },
  CLI_CODING_INPUT_LIMIT: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CODING_INPUT_LIMIT', p, l) }) },
  CLI_CODING_INPUT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CODING_INPUT_INVALID', p, l) }) },
  CLI_CODING_INPUT_TTY: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CODING_INPUT_TTY', p, l) }) },
  CLI_CODING_INPUT_UNAVAILABLE: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_CODING_INPUT_UNAVAILABLE', p, l) }) },
  CLI_GRAPH_INPUT_LIMIT: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_GRAPH_INPUT_LIMIT', { ...p, limit: p.limit ?? t('cli.graph.configuredLimit', {}, l) }, l) }) },
  CLI_GRAPH_INPUT_INVALID: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_GRAPH_INPUT_INVALID', { ...p, path: p.path ?? 'graph', reason: p.reason ?? t('cli.graph.expected', {}, l) }, l) }) },
  CLI_GRAPH_INPUT_TTY: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_GRAPH_INPUT_TTY', p, l) }) },
  CLI_GRAPH_INPUT_UNAVAILABLE: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_GRAPH_INPUT_UNAVAILABLE', p, l) }) },
  INSTALL_INSPECTION_CONTROL_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_INSPECTION_CONTROL_REQUIRED', p, l) }) },
  INSTALL_INSPECTION_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_INSPECTION_UNAVAILABLE', p, l) }) },
  INSTALLATION_EVIDENCE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_EVIDENCE_INVALID', p, l) }) },
  INSTALLATION_EVIDENCE_IMAGES: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_EVIDENCE_IMAGES', p, l) }) },
  INSTALLATION_EVIDENCE_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_EVIDENCE_CHANGED', p, l) }) },
  INSTALLATION_ARTIFACT_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_ARTIFACT_INVALID', p, l) }) },
  INSTALLATION_ARTIFACT_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_ARTIFACT_UNSAFE', p, l) }) },
  INSTALLATION_ARTIFACT_LIMIT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_ARTIFACT_LIMIT', p, l) }) },
  INSTALLATION_ARTIFACT_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_ARTIFACT_CHANGED', p, l) }) },
  INSTALLATION_ARTIFACT_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_ARTIFACT_UNAVAILABLE', p, l) }) },
  DOCKER_IMAGE_PROBE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.DOCKER_IMAGE_PROBE_INVALID', p, l) }) },
  DOCKER_IMAGE_PROBE_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.DOCKER_IMAGE_PROBE_UNAVAILABLE', p, l) }) },
  DOCKER_IMAGE_PROBE_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.DOCKER_IMAGE_PROBE_CHANGED', p, l) }) },
  INSTALL_PROFILE_REQUIRED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PROFILE_REQUIRED', p, l) }) },
  INSTALL_PREVIEW_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PREVIEW_UNAVAILABLE', p, l) }) },
  INSTALL_PROFILE_SOURCE_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PROFILE_SOURCE_UNAVAILABLE', p, l) }) },
  INSTALL_PROFILE_SOURCE_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PROFILE_SOURCE_UNSAFE', p, l) }) },
  INSTALL_PROFILE_SOURCE_TOO_LARGE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PROFILE_SOURCE_TOO_LARGE', p, l) }) },
  INSTALL_PROFILE_SOURCE_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PROFILE_SOURCE_CHANGED', p, l) }) },
  INSTALL_PROFILE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALL_PROFILE_INVALID', p, l) }) },
  INSTALLATION_PROFILE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_INVALID', p, l) }) },
  INSTALLATION_PROFILE_DIGEST: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_DIGEST', p, l) }) },
  INSTALLATION_PROFILE_CONFIG: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_CONFIG', p, l) }) },
  INSTALLATION_PROFILE_REGISTRY: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_REGISTRY', p, l) }) },
  INSTALLATION_PROFILE_ADAPTER: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_ADAPTER', p, l) }) },
  INSTALLATION_PROFILE_EVALUATOR: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_EVALUATOR', p, l) }) },
  INSTALLATION_PROFILE_POOL: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_POOL', p, l) }) },
  INSTALLATION_PROFILE_POLICY: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_POLICY', p, l) }) },
  INSTALLATION_PROFILE_SHUTDOWN: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_SHUTDOWN', p, l) }) },
  // C12 Q8 follow-up (owner 2026-09-27): installation owns its typed require-approval refusal, same 'config' category
  // (exit 78) as its INSTALLATION_PROFILE_* siblings above, instead of the shared cross-module POLICY_APPROVAL_UNSUPPORTED
  // ('error' category, exit 1) used by the other 9 authorization points outside the operation catalog.
  // Locale key not yet present (locale files are lead-owned, common); see i18n-delta.json for suggested en/tr text.
  INSTALLATION_PROFILE_APPROVAL_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_APPROVAL_UNSUPPORTED', p, l) }) },
  INSTALLATION_PROFILE_PATHS: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PROFILE_PATHS', p, l) }) },
  BOOTSTRAP_STATE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.BOOTSTRAP_STATE_INVALID', p, l) }) },
  BOOTSTRAP_STATE_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.BOOTSTRAP_STATE_UNSAFE', p, l) }) },
  BOOTSTRAP_STATE_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.BOOTSTRAP_STATE_CHANGED', p, l) }) },
  BOOTSTRAP_INSTALLATION_INCOMPLETE: { category: 'config', render: (p, l) => ({ message: t('error.BOOTSTRAP_INSTALLATION_INCOMPLETE', p, l) }) },
  BOOTSTRAP_STATE_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.BOOTSTRAP_STATE_UNAVAILABLE', p, l) }) },
  BOOTSTRAP_STATE_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.BOOTSTRAP_STATE_UNSUPPORTED', p, l) }) },
  INSTALLATION_JOURNAL_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_INVALID', p, l) }) },
  INSTALLATION_JOURNAL_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_UNSAFE', p, l) }) },
  INSTALLATION_JOURNAL_CONFLICT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_CONFLICT', p, l) }) },
  INSTALLATION_JOURNAL_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_UNAVAILABLE', p, l) }) },
  INSTALLATION_JOURNAL_BUSY: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_BUSY', p, l) }) },
  INSTALLATION_JOURNAL_OUTCOME_UNKNOWN: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_OUTCOME_UNKNOWN', p, l) }) },
  INSTALLATION_JOURNAL_EXPIRED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_EXPIRED', p, l) }) },
  INSTALLATION_JOURNAL_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_JOURNAL_UNSUPPORTED', p, l) }) },
  INSTALLATION_FILE_CONFLICT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_FILE_CONFLICT', p, l) }) },
  INSTALLATION_FILE_UNSAFE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_FILE_UNSAFE', p, l) }) },
  INSTALLATION_FILE_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_FILE_INVALID', p, l) }) },
  INSTALLATION_FILE_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_FILE_UNAVAILABLE', p, l) }) },
  INSTALLATION_FILE_OUTCOME_UNKNOWN: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_FILE_OUTCOME_UNKNOWN', p, l) }) },
  INSTALLATION_FILE_UNSUPPORTED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_FILE_UNSUPPORTED', p, l) }) },
  INSTALLATION_LEDGER_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_LEDGER_INVALID', p, l) }) },
  INSTALLATION_LEDGER_CONFLICT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_LEDGER_CONFLICT', p, l) }) },
  INSTALLATION_LEDGER_CORRUPT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_LEDGER_CORRUPT', p, l) }) },
  INSTALLATION_LEDGER_UNAVAILABLE: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_LEDGER_UNAVAILABLE', p, l) }) },
  INSTALLATION_LEDGER_OUTCOME_UNKNOWN: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_LEDGER_OUTCOME_UNKNOWN', p, l) }) },
  INSTALLATION_RECOVERY_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_RECOVERY_INVALID', p, l) }) },
  INSTALLATION_RECOVERY_CONSENT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_RECOVERY_CONSENT', p, l) }) },
  INSTALLATION_RECOVERY_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_RECOVERY_CHANGED', p, l) }) },
  INSTALLATION_PUBLICATION_INVALID: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PUBLICATION_INVALID', p, l) }) },
  INSTALLATION_PUBLICATION_CONFLICT: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PUBLICATION_CONFLICT', p, l) }) },
  INSTALLATION_PUBLICATION_CHANGED: { category: 'config', render: (p, l) => ({ message: t('error.INSTALLATION_PUBLICATION_CHANGED', p, l) }) },
  WORKER_VERSION_COUNTER_TAKEN: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_VERSION_COUNTER_TAKEN', { detail: '', ...p }, l) }) },
  WORKER_VERSION_TAKEN: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_VERSION_TAKEN', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_VERSION_CHECK_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_VERSION_CHECK_FAILED', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_VERSION_CHECK_TIMEOUT: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_VERSION_CHECK_TIMEOUT', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_COMMAND_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_COMMAND_FAILED', { detail: '', ...p }, l) }) },
  WORKER_DAEMON_CHANGED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_DAEMON_CHANGED', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_ID_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_ID_INVALID', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_ID_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_ID_MISMATCH', { detail: '', ...p }, l) }) },
  WORKER_LABEL_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_LABEL_MISMATCH', { detail: '', ...p }, l) }) },
  WORKER_TAG_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_TAG_MISMATCH', { detail: '', ...p }, l) }) },
  WORKER_RECEIPT_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_RECEIPT_INVALID', { detail: '', ...p }, l) }) },
  WORKER_RECEIPT_DIRECTORY_UNAVAILABLE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_RECEIPT_DIRECTORY_UNAVAILABLE', { detail: '', ...p }, l) }) },
  WORKER_HISTORY_COUNTER: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_HISTORY_COUNTER', { detail: '', ...p }, l) }) },
  WORKER_HISTORY_EMPTY: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_HISTORY_EMPTY', { detail: '', ...p }, l) }) },
  WORKER_HISTORY_IDS: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_HISTORY_IDS', { detail: '', ...p }, l) }) },
  WORKER_HISTORY_LINE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_HISTORY_LINE', { detail: '', ...p }, l) }) },
  WORKER_HISTORY_MISMATCH: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_HISTORY_MISMATCH', { detail: '', ...p }, l) }) },
  WORKER_HISTORY_ORDER: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_HISTORY_ORDER', { detail: '', ...p }, l) }) },
  WORKER_RECIPE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_RECIPE_INVALID', { detail: '', ...p }, l) }) },
  WORKER_RECIPE_PREVIOUS: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_RECIPE_PREVIOUS', { detail: '', ...p }, l) }) },
  WORKER_RECIPE_REPOSITORY: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_RECIPE_REPOSITORY', { detail: '', ...p }, l) }) },
  WORKER_RECIPE_VERSION: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_RECIPE_VERSION', { detail: '', ...p }, l) }) },
  WORKER_CLI_INCOMPATIBLE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_CLI_INCOMPATIBLE', { detail: '', ...p }, l) }) },
  WORKER_VERSION_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_VERSION_INVALID', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_SOURCE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_SOURCE_INVALID', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_CONTEXT_EXISTS: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_CONTEXT_EXISTS', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_CONTEXT_UNSAFE: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_CONTEXT_UNSAFE', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_BUILD_FAILED: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_BUILD_FAILED', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_BUILD_TIMEOUT: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_BUILD_TIMEOUT', { detail: '', ...p }, l) }) },
  WORKER_IMAGE_RECEIPT_MISSING: { category: 'error', render: (p, l) => ({ message: t('error.WORKER_IMAGE_RECEIPT_MISSING', { detail: '', ...p }, l) }) },
  TOOLCHAIN_RECIPE_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TOOLCHAIN_RECIPE_INVALID', { detail: '', ...p }, l) }) },
  TOOLCHAIN_HISTORY_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TOOLCHAIN_HISTORY_INVALID', { detail: '', ...p }, l) }) },
  TOOLCHAIN_RECEIPT_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TOOLCHAIN_RECEIPT_INVALID', { detail: '', ...p }, l) }) },
  TOOLCHAIN_PLAN_INVALID: { category: 'error', render: (p, l) => ({ message: t('error.TOOLCHAIN_PLAN_INVALID', { detail: '', ...p }, l) }) },
  CLI_USAGE: { category: 'usage', render: (p, l) => ({ message: t('error.CLI_USAGE', { ...p, command: p.command ?? 'deckent', usage: p.usage ?? t('cli.usage.help', {}, l), flag: p.flag ?? t('cli.usage.arguments', {}, l) }, l) }) },
});
for (const definition of Object.values(definitions)) Object.freeze(definition);
export const ERROR_CODES: readonly string[] = Object.freeze(Object.keys(definitions));
export const ErrorRegistry = Object.freeze({
  has(code: string): boolean { return Object.hasOwn(definitions, code); },
  get(code: string, locale: Locale = resolveLocale(), params: Params = {}): Readonly<ErrorEntry> | undefined {
    const definition = Object.hasOwn(definitions, code) ? definitions[code] : undefined;
    return definition ? Object.freeze(definition.render({ floor: NODE_ENGINE_RANGE, major: NODE_ENGINE_RANGE.match(/\d+/)?.[0] ?? NODE_ENGINE_RANGE, ...params }, locale)) : undefined;
  },
  getAll(locale: Locale = resolveLocale()): Map<string, Readonly<ErrorEntry>> {
    return new Map(ERROR_CODES.map(code => [code, this.get(code, locale)!]));
  },
  createError(code: string, options: { message?: string; suggestion?: string; params?: Params; locale?: Locale; cause?: unknown } = {}): DeckentError {
    const locale = options.locale ?? resolveLocale();
    const entry = this.get(code, locale, options.params);
    const category = Object.hasOwn(definitions, code) ? definitions[code]!.category : 'error';
    return new DeckentError(code, options.message ?? entry?.message ?? t('error.unknown', { code }, locale),
      options.suggestion ?? entry?.suggestion, undefined, entry?.whatHappened, entry?.why, entry?.howToFix, category,
      options.cause === undefined ? undefined : { cause: options.cause },
      options.message === undefined ? target => this.get(code, target, options.params) ?? { message: t('error.unknown', { code }, target) } : undefined, Object.freeze({ ...options.params }));
  },
});
