import { t, type Locale } from '#platform/index.js';
import type { PanelLabels } from '#surfaces/core/terminal-panels/index.js';
import { pickerLabels } from './work-labels.js';

/** Catalog words of the `/mode`, `/config`, `/mcp` (T3 L4), `/model` and `/provider` (T4) windows, EN and TR; the panels themselves never call the catalog. */
export function terminalPanelLabels(locale: Locale): PanelLabels {
  return {
    picker: pickerLabels(locale), position: t('terminal.window.position', {}, locale), loading: t('tui.panel.loading', {}, locale),
    mode: { title: t('tui.panel.mode.title', {}, locale), hints: t('tui.panel.mode.hints', {}, locale), current: t('tui.panel.current', {}, locale),
      stops: { standart: t('terminal.mode.stop.standart', {}, locale), 'ask-edits': t('terminal.mode.stop.ask-edits', {}, locale), 'full-auto': t('terminal.mode.stop.full-auto', {}, locale),
        'full-access': t('terminal.mode.stop.full-access', {}, locale) },
      effect: { standart: t('terminal.mode.effect.standart', {}, locale), 'ask-edits': t('tui.panel.mode.effect.askEdits', {}, locale), 'full-auto': t('terminal.mode.effect.full-auto', {}, locale),
        'full-access': t('terminal.mode.effect.full-access', {}, locale) },
      fullAccessGrant: t('terminal.mode.fullAccessGrant', {}, locale), fullAutoOff: t('tui.panel.mode.fullAutoOff', {}, locale), unsupported: t('terminal.mode.unsupported', {}, locale),
      now: t('tui.panel.mode.now', {}, locale), inert: t('tui.panel.mode.inert', {}, locale) },
    config: { records: { edit: t('config.records.edit', {}, locale), add: t('config.records.add', {}, locale), remove: t('config.records.remove', {}, locale), import: t('config.records.import', {}, locale), save: t('config.records.save', {}, locale), before: t('config.records.before', {}, locale), after: t('config.records.after', {}, locale), browse: t('config.records.browse', {}, locale), select: t('config.records.select', {}, locale), empty: t('config.records.empty', {}, locale) }, summary: t('config.select.summary', {}, locale), hints: t('tui.panel.config.hints', {}, locale), scopes: { project: t('tui.panel.config.scope.project', {}, locale), global: t('tui.panel.config.scope.global', {}, locale) },
      general: t('tui.panel.config.general', {}, locale), current: t('tui.panel.current', {}, locale), expected: t('tui.panel.config.expected', {}, locale),
      freeEntry: t('tui.panel.config.freeEntry', {}, locale), unset: t('tui.panel.config.unset', {}, locale), entryTitle: t('tui.panel.config.entryTitle', {}, locale),
      entryHint: t('tui.panel.config.entryHint', {}, locale), stepper: t('config.select.stepper', {}, locale),
      stepperHint: t('config.select.stepperHint', {}, locale), regenerate: t('config.select.regenerate', {}, locale),
      preview: t('config.select.preview', {}, locale), previewHint: t('config.select.previewHint', {}, locale) },
    mcp: { title: t('tui.panel.mcp.title', {}, locale), hints: t('tui.panel.mcp.hints', {}, locale), add: t('tui.panel.mcp.add', {}, locale), addDetail: t('tui.panel.mcp.addDetail', {}, locale),
      none: t('tui.panel.mcp.empty', {}, locale),
      actions: { detail: t('tui.panel.mcp.action.detail', {}, locale), revoke: t('tui.panel.mcp.action.revoke', {}, locale), approve: t('tui.panel.mcp.action.approve', {}, locale),
        reconnect: t('tui.panel.mcp.action.reconnect', {}, locale), remove: t('tui.panel.mcp.action.remove', {}, locale) },
      step: t('tui.panel.mcp.step', {}, locale),
      steps: { transport: t('tui.panel.mcp.steps.transport', {}, locale), name: t('tui.panel.mcp.steps.name', {}, locale), command: t('tui.panel.mcp.steps.command', {}, locale),
        url: t('tui.panel.mcp.steps.url', {}, locale), args: t('tui.panel.mcp.steps.args', {}, locale), env: t('tui.panel.mcp.steps.env', {}, locale), headers: t('tui.panel.mcp.steps.headers', {}, locale),
        realm: t('tui.panel.mcp.steps.realm', {}, locale), scope: t('tui.panel.mcp.steps.scope', {}, locale) },
      entryHints: { name: t('tui.panel.mcp.entry.name', {}, locale), command: t('tui.panel.mcp.entry.command', {}, locale), url: t('tui.panel.mcp.entry.url', {}, locale),
        args: t('tui.panel.mcp.entry.args', {}, locale), env: t('tui.panel.mcp.entry.env', {}, locale), headers: t('tui.panel.mcp.entry.headers', {}, locale) },
      pairInvalid: t('tui.panel.mcp.pairInvalid', {}, locale), empty: t('tui.panel.mcp.required', {}, locale), trustKeys: t('tui.panel.mcp.trust.keys', {}, locale) },
    model: { hints: t('tui.panel.model.hints', {}, locale), session: t('tui.panel.model.session', {}, locale), sessionAndDefault: t('tui.panel.model.sessionAndDefault', {}, locale),
      pinnedMark: t('tui.panel.model.pinnedMark', {}, locale), configuredMark: t('tui.panel.model.configuredMark', {}, locale), pinned: t('tui.panel.model.pinned', {}, locale),
      shadowTitle: t('tui.panel.model.shadowTitle', {}, locale), shadowRemove: t('tui.panel.model.shadowRemove', {}, locale),
      shadowAlign: t('tui.panel.model.shadowAlign', {}, locale), shadowKeep: t('tui.panel.model.shadowKeep', {}, locale),
      switch: { title: t('tui.panel.model.switch.title', {}, locale), fresh: t('tui.panel.model.switch.fresh', {}, locale), keep: t('tui.panel.model.switch.keep', {}, locale),
        freshDone: t('tui.panel.model.switch.freshDone', {}, locale), keepDone: t('tui.panel.model.switch.keepDone', {}, locale) } },
    provider: { title: t('tui.panel.provider.title', {}, locale), hints: t('tui.panel.provider.hints', {}, locale),
      actions: { connect: t('tui.panel.provider.action.connect', {}, locale), replace: t('tui.panel.provider.action.replace', {}, locale),
        disconnect: t('tui.panel.provider.action.disconnect', {}, locale), model: t('tui.panel.provider.action.model', {}, locale) },
      modelTitle: t('tui.panel.provider.modelTitle', {}, locale), modelEmpty: t('tui.panel.provider.modelEmpty', {}, locale), keyName: t('tui.panel.provider.keyName', {}, locale),
      endpointTitle: t('tui.panel.provider.endpointTitle', {}, locale), endpointHint: t('tui.panel.provider.endpointHint', {}, locale),
      endpointOther: t('tui.panel.provider.endpointOther', {}, locale), previewTitle: t('tui.panel.provider.previewTitle', {}, locale),
      previewAddress: t('tui.panel.provider.previewAddress', {}, locale), previewCheck: t('tui.panel.provider.previewCheck', {}, locale),
      previewKeys: t('tui.panel.provider.previewKeys', {}, locale),
      keyTitle: t('tui.panel.provider.keyTitle', {}, locale), keyHint: t('tui.panel.provider.keyHint', {}, locale), keyOptionalHint: t('tui.panel.provider.keyOptionalHint', {}, locale),
      keyRequired: t('tui.panel.provider.keyRequired', {}, locale), checking: t('tui.panel.provider.checking', {}, locale), resultHints: t('tui.panel.provider.resultHints', {}, locale),
      disconnectTitle: t('tui.panel.provider.disconnectTitle', {}, locale), disconnectKeys: t('tui.panel.provider.disconnectKeys', {}, locale),
      empty: t('tui.panel.provider.empty', {}, locale) },
    budget: { create: t('tui.panel.budget.create', {}, locale), change: t('tui.panel.budget.change', {}, locale), changeDetail: t('tui.panel.budget.changeDetail', {}, locale),
      preset: t('tui.panel.budget.preset', {}, locale), other: t('tui.panel.budget.other', {}, locale), stepperTitle: t('tui.panel.budget.stepperTitle', {}, locale),
      hints: t('tui.panel.budget.hints', {}, locale), confirmTitle: t('tui.panel.budget.confirmTitle', {}, locale), confirm: t('tui.panel.budget.confirm', {}, locale),
      confirmUnfreeze: t('tui.panel.budget.confirmUnfreeze', {}, locale), cancel: t('tui.panel.budget.cancel', {}, locale), belowSettled: t('tui.panel.budget.belowSettled', {}, locale) },
    policy: { title: t('policy.mcp.title', {}, locale), scope: t('policy.mcp.scope', {}, locale), groups: t('policy.mcp.groups', {}, locale), preview: t('policy.mcp.preview', {}, locale),
      grant: t('policy.mcp.grant', {}, locale), revoke: t('policy.mcp.revoke', {}, locale), confirm: t('policy.mcp.confirm', {}, locale), back: t('policy.mcp.back', {}, locale),
      hints: t('policy.mcp.hints', {}, locale), empty: t('policy.mcp.empty', {}, locale) },
    cache: { entry: t('tui.panel.cache.entry', {}, locale), title: t('tui.panel.cache.title', {}, locale), confirm: t('tui.panel.cache.confirm', {}, locale),
      cancel: t('tui.panel.cache.cancel', {}, locale), hints: t('tui.panel.cache.hints', {}, locale) },
  };
}
