export { PACKAGE_NAME, PACKAGE_VERSION } from '#platform/core/common/index.js';
export { resolveLocale, t } from '#platform/core/i18n/index.js';
export type { Locale, MessageKey } from '#platform/core/i18n/index.js';
export { DECKENT_DIR, CONFIG_FILE, PROJECT_CONFIG_PATH, CONFIG_SCHEMA_VERSION, CONFIG_CONTRACT_SINCE, OUTPUT_MODES } from '#platform/core/common/index.js';
export type { OutputMode } from '#platform/core/common/index.js';
export { DECKENT_VERSION, NODE_ENGINE_RANGE } from '#platform/core/common/index.js';
export { SUPPORTED_LANGUAGES } from '#platform/core/i18n/index.js';
export type { Params } from '#platform/core/i18n/index.js';
export { DeckentError } from '#platform/core/errors/index.js';
export type { ErrorCategory } from '#platform/core/errors/index.js';
export { ErrorRegistry, ERROR_CODES, createCrossVerifyContractError, createExecutionAuthorityError, createExecutionAdmissionError, createDockerLifecycleError } from '#platform/core/errors/index.js';
export { EXIT_CODES, exitCodeFor } from '#platform/core/errors/index.js';
export type { ExitCode } from '#platform/core/errors/index.js';
export { lintErrorRegistry, assertErrorRegistry } from '#platform/core/errors/index.js';
export { formatHumanError, redactSensitive, buildCrashArtifact, writeCrashArtifact, reportFatal } from '#platform/core/errors/index.js';
export type { CrashArtifactV1 } from '#platform/core/errors/index.js';
export { ENVIRONMENT_KEYS, envValue } from '#platform/core/host/index.js';
export type { Environment } from '#platform/core/host/index.js';
export { normalizeGlobalScopePlatform, resolveGlobalScopePaths, resolveGlobalConfigPaths, resolveGlobalConfigReadPath } from '#platform/core/host/index.js';
export type { GlobalScopePlatform, GlobalScopePaths } from '#platform/core/host/index.js';
export { resolveProductPaths } from '#platform/core/host/index.js';
export { detectHostMemory, suggestMaxWorkers, calcRecommendedMaxWorkers, suggestMaxWorkersFromCapacity, getSystemProfile } from '#platform/core/host/index.js';
export { detectEnvironment } from '#platform/core/host/index.js';
export { validatePath, validateExistingPath, validateTaskId } from '#platform/core/validate/index.js';
export { deepMerge, readJsonFile, writeJsonAtomic } from '#platform/core/utils/index.js';
export { formatDuration, estimateRemaining } from '#platform/core/utils/index.js';
export { CORE_SCHEMA, registerConfigSection } from '#platform/core/config/index.js';
export type { DeckentConfig, CoreConfig, ConfigSectionOptions } from '#platform/core/config/index.js';
export { createDefaultConfig } from '#platform/core/config/index.js';
export { ConfigValidationError } from '#platform/core/config/index.js';
export type { ConfigWarning } from '#platform/core/config/index.js';
export { validateConfig } from '#platform/core/config/index.js';
export { resolveConfigSecrets } from '#platform/core/config/index.js';
export { configDisplayView } from '#platform/core/config/index.js';
export { loadConfig, loadGlobalConfig, clearConfigCache } from '#platform/core/config/index.js';
export type { ResolvedConfig, ConfigLoadOptions } from '#platform/core/config/index.js';
export { saveGlobalConfig, writeConfig, withConfigWriteLock, pruneConfigBackups } from '#platform/core/config/index.js';
export { healCorruptProjectConfig } from '#platform/core/config/index.js';
export { getConfigMetadata } from '#platform/core/config/index.js';
export { getConfigValue } from '#platform/core/config/index.js';
export { resolveLocalOsActorId, resolveLocalOsPrincipal, principalToActor, assessActorAssurance, assertActorAssurance } from '#platform/core/identity/index.js';
export type { PrincipalEvidence, ActorContext } from '#platform/core/identity/index.js';
export { isValidTenantId, tenantIsolationPath, resolveTenant, resolveCallerTenant, withTenant, currentTenant, tenantPath } from '#platform/core/identity/index.js';
export { colorTier, shouldUseColor, stripAnsi } from '#platform/core/output/index.js';
export { formatValue, formatTable, formatStatus, readMemoryKnowledge } from '#platform/core/output/index.js';
export { emit, createEmitter } from '#platform/core/output/index.js';
export type { OutputSink, EmitOptions } from '#platform/core/output/index.js';
export { LOCALES, MESSAGE_KEYS, MESSAGE_REGISTRY, createMessageRegistry } from '#platform/core/i18n/index.js';
export type { MessageFamily, MessageRegistry } from '#platform/core/i18n/index.js';
export { getConfigFieldDefault } from '#platform/core/config-fields/index.js';
export { resolveProductLayout, productResourcePath, LayoutError } from '#platform/core/host/index.js';
export type { ProductLayout, ProductLayoutInput, ProductResource } from '#platform/core/host/index.js';
export type { SecretResolver, SecretResolution } from '#platform/core/config/index.js';
export { inspectProductLayout, type ProductPathInspection } from '#platform/core/host/index.js';
export { inspectProductPaths } from '#platform/core/config/index.js';
export { SQLITE_STORAGE_OPTIONS } from '#platform/core/config-fields/index.js';
export { prepareProductFile, inspectProductFile, prepareProductDirectory, inspectProductDirectory, ManagedFileError } from '#platform/core/managed-files/index.js';
export { DOCKER_EXECUTION_SETTINGS, GIT_EXECUTION_SETTINGS, ARTIFACT_STORAGE_LIMITS } from '#platform/core/config-fields/index.js';
