export type WorkspaceAdoptionErrorCode = 'ADOPTION_TARGET_DENIED' | 'ADOPTION_TARGET_MISSING' | 'ADOPTION_TARGET_CHECKED_OUT'
  | 'ADOPTION_BASE_CHANGED' | 'ADOPTION_NOT_DELIVERED' | 'ADOPTION_NOT_ACCEPTED' | 'ADOPTION_TARGET_BUSY' | 'ADOPTION_SUPERSEDED'
  | 'ADOPTION_TARGET_MOVED' | 'ADOPTION_CONFLICT' | 'ADOPTION_CORRUPT' | 'ADOPTION_VERIFICATION_FAILED' | 'ADOPTION_VERIFICATION_PENDING'
  | 'ADOPTION_VERIFICATION_UNSETTLED' | 'ADOPTION_VERIFICATION_CANCELLED' | 'ADOPTION_VERIFICATION_MISMATCH';
export class WorkspaceAdoptionError extends Error {
  constructor(readonly code: WorkspaceAdoptionErrorCode, options?: ErrorOptions) { super(code, options); this.name = 'WorkspaceAdoptionError'; }
}
